
package mep.creation.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ItfAppelSvc", targetNamespace = "http://service.isiwebinterface.ass.inf.suo.fr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ItfAppelSvc {


    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @param arg11
     * @param arg12
     * @param arg10
     * @param arg6
     * @param arg7
     * @param arg8
     * @param arg9
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "enregistrerDEPUlis", targetNamespace = "http://service.isiwebinterface.ass.inf.suo.fr/", className = "client.EnregistrerDEPUlis")
    @ResponseWrapper(localName = "enregistrerDEPUlisResponse", targetNamespace = "http://service.isiwebinterface.ass.inf.suo.fr/", className = "client.EnregistrerDEPUlisResponse")
    public String enregistrerDEPUlis(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        XMLGregorianCalendar arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        XMLGregorianCalendar arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        Long arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        Long arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        String arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        Long arg9,
        @WebParam(name = "arg10", targetNamespace = "")
        String arg10,
        @WebParam(name = "arg11", targetNamespace = "")
        String arg11,
        @WebParam(name = "arg12", targetNamespace = "")
        Long arg12);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<client.Appel>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenirListeAppelParNatureEtDates", targetNamespace = "http://service.isiwebinterface.ass.inf.suo.fr/", className = "client.ObtenirListeAppelParNatureEtDates")
    @ResponseWrapper(localName = "obtenirListeAppelParNatureEtDatesResponse", targetNamespace = "http://service.isiwebinterface.ass.inf.suo.fr/", className = "client.ObtenirListeAppelParNatureEtDatesResponse")
    public List<Appel> obtenirListeAppelParNatureEtDates(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        XMLGregorianCalendar arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        XMLGregorianCalendar arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "enregistrerAlarmeHyperviseur", targetNamespace = "http://service.isiwebinterface.ass.inf.suo.fr/", className = "client.EnregistrerAlarmeHyperviseur")
    @ResponseWrapper(localName = "enregistrerAlarmeHyperviseurResponse", targetNamespace = "http://service.isiwebinterface.ass.inf.suo.fr/", className = "client.EnregistrerAlarmeHyperviseurResponse")
    public String enregistrerAlarmeHyperviseur(
        @WebParam(name = "arg0", targetNamespace = "")
        Alarme arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<client.Appel>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListeAppelParIdPere", targetNamespace = "http://service.isiwebinterface.ass.inf.suo.fr/", className = "client.GetListeAppelParIdPere")
    @ResponseWrapper(localName = "getListeAppelParIdPereResponse", targetNamespace = "http://service.isiwebinterface.ass.inf.suo.fr/", className = "client.GetListeAppelParIdPereResponse")
    public List<Appel> getListeAppelParIdPere(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param appelcode
     * @return
     *     returns client.Appel
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAppelParCode", targetNamespace = "http://service.isiwebinterface.ass.inf.suo.fr/", className = "client.GetAppelParCode")
    @ResponseWrapper(localName = "getAppelParCodeResponse", targetNamespace = "http://service.isiwebinterface.ass.inf.suo.fr/", className = "client.GetAppelParCodeResponse")
    public Appel getAppelParCode(
        @WebParam(name = "appelcode", targetNamespace = "")
        String appelcode);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<client.Appel>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "rechercherParDateDeMiseAJourMinimum", targetNamespace = "http://service.isiwebinterface.ass.inf.suo.fr/", className = "client.RechercherParDateDeMiseAJourMinimum")
    @ResponseWrapper(localName = "rechercherParDateDeMiseAJourMinimumResponse", targetNamespace = "http://service.isiwebinterface.ass.inf.suo.fr/", className = "client.RechercherParDateDeMiseAJourMinimumResponse")
    public List<Appel> rechercherParDateDeMiseAJourMinimum(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        XMLGregorianCalendar arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws TechniqueException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "enregistrerLigneCommandeDivalto", targetNamespace = "http://service.isiwebinterface.ass.inf.suo.fr/", className = "client.EnregistrerLigneCommandeDivalto")
    @ResponseWrapper(localName = "enregistrerLigneCommandeDivaltoResponse", targetNamespace = "http://service.isiwebinterface.ass.inf.suo.fr/", className = "client.EnregistrerLigneCommandeDivaltoResponse")
    public String enregistrerLigneCommandeDivalto(
        @WebParam(name = "arg0", targetNamespace = "")
        CommandeDTO arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<LigneCommandeDTO> arg1)
        throws TechniqueException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<client.Appel>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "rechercherIncidentParDateClotureAlarmeRenseigne", targetNamespace = "http://service.isiwebinterface.ass.inf.suo.fr/", className = "client.RechercherIncidentParDateClotureAlarmeRenseigne")
    @ResponseWrapper(localName = "rechercherIncidentParDateClotureAlarmeRenseigneResponse", targetNamespace = "http://service.isiwebinterface.ass.inf.suo.fr/", className = "client.RechercherIncidentParDateClotureAlarmeRenseigneResponse")
    public List<Appel> rechercherIncidentParDateClotureAlarmeRenseigne(
        @WebParam(name = "arg0", targetNamespace = "")
        XMLGregorianCalendar arg0);

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @param arg13
     * @param arg11
     * @param arg12
     * @param arg10
     * @param arg6
     * @param arg7
     * @param arg8
     * @param arg9
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "enregistrerRFCUlis", targetNamespace = "http://service.isiwebinterface.ass.inf.suo.fr/", className = "client.EnregistrerRFCUlis")
    @ResponseWrapper(localName = "enregistrerRFCUlisResponse", targetNamespace = "http://service.isiwebinterface.ass.inf.suo.fr/", className = "client.EnregistrerRFCUlisResponse")
    public String enregistrerRFCUlis(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        XMLGregorianCalendar arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        XMLGregorianCalendar arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        Long arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        Long arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        String arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        String arg9,
        @WebParam(name = "arg10", targetNamespace = "")
        String arg10,
        @WebParam(name = "arg11", targetNamespace = "")
        String arg11,
        @WebParam(name = "arg12", targetNamespace = "")
        String arg12,
        @WebParam(name = "arg13", targetNamespace = "")
        Long arg13);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<client.Appel>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "rechercherAppelPortail", targetNamespace = "http://service.isiwebinterface.ass.inf.suo.fr/", className = "client.RechercherAppelPortail")
    @ResponseWrapper(localName = "rechercherAppelPortailResponse", targetNamespace = "http://service.isiwebinterface.ass.inf.suo.fr/", className = "client.RechercherAppelPortailResponse")
    public List<Appel> rechercherAppelPortail(
        @WebParam(name = "arg0", targetNamespace = "")
        XMLGregorianCalendar arg0);

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @param arg11
     * @param arg10
     * @param arg6
     * @param arg7
     * @param arg8
     * @param arg9
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "enregistrerDEPDivalto", targetNamespace = "http://service.isiwebinterface.ass.inf.suo.fr/", className = "client.EnregistrerDEPDivalto")
    @ResponseWrapper(localName = "enregistrerDEPDivaltoResponse", targetNamespace = "http://service.isiwebinterface.ass.inf.suo.fr/", className = "client.EnregistrerDEPDivaltoResponse")
    public String enregistrerDEPDivalto(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        XMLGregorianCalendar arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        XMLGregorianCalendar arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        String arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        String arg9,
        @WebParam(name = "arg10", targetNamespace = "")
        String arg10,
        @WebParam(name = "arg11", targetNamespace = "")
        String arg11);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<client.Appel>
     */
    @WebMethod(operationName = "rechercherAppelParDI_Objet")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "rechercherAppelParDI_Objet", targetNamespace = "http://service.isiwebinterface.ass.inf.suo.fr/", className = "client.RechercherAppelParDIObjet")
    @ResponseWrapper(localName = "rechercherAppelParDI_ObjetResponse", targetNamespace = "http://service.isiwebinterface.ass.inf.suo.fr/", className = "client.RechercherAppelParDIObjetResponse")
    public List<Appel> rechercherAppelParDIObjet(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        Long arg3);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "enregistrerAppel", targetNamespace = "http://service.isiwebinterface.ass.inf.suo.fr/", className = "client.EnregistrerAppel")
    @ResponseWrapper(localName = "enregistrerAppelResponse", targetNamespace = "http://service.isiwebinterface.ass.inf.suo.fr/", className = "client.EnregistrerAppelResponse")
    public String enregistrerAppel(
        @WebParam(name = "arg0", targetNamespace = "")
        Appel arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEmailEquipeDeploiementAppel", targetNamespace = "http://service.isiwebinterface.ass.inf.suo.fr/", className = "client.GetEmailEquipeDeploiementAppel")
    @ResponseWrapper(localName = "getEmailEquipeDeploiementAppelResponse", targetNamespace = "http://service.isiwebinterface.ass.inf.suo.fr/", className = "client.GetEmailEquipeDeploiementAppelResponse")
    public String getEmailEquipeDeploiementAppel(
        @WebParam(name = "arg0", targetNamespace = "")
        Appel arg0);

    /**
     * 
     * @param appelid
     * @return
     *     returns client.Appel
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAppelParId", targetNamespace = "http://service.isiwebinterface.ass.inf.suo.fr/", className = "client.GetAppelParId")
    @ResponseWrapper(localName = "getAppelParIdResponse", targetNamespace = "http://service.isiwebinterface.ass.inf.suo.fr/", className = "client.GetAppelParIdResponse")
    public Appel getAppelParId(
        @WebParam(name = "appelid", targetNamespace = "")
        long appelid);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<client.Appel>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "rechercherAppelParSolution", targetNamespace = "http://service.isiwebinterface.ass.inf.suo.fr/", className = "client.RechercherAppelParSolution")
    @ResponseWrapper(localName = "rechercherAppelParSolutionResponse", targetNamespace = "http://service.isiwebinterface.ass.inf.suo.fr/", className = "client.RechercherAppelParSolutionResponse")
    public List<Appel> rechercherAppelParSolution(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<client.Appel>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListeAppelParId", targetNamespace = "http://service.isiwebinterface.ass.inf.suo.fr/", className = "client.GetListeAppelParId")
    @ResponseWrapper(localName = "getListeAppelParIdResponse", targetNamespace = "http://service.isiwebinterface.ass.inf.suo.fr/", className = "client.GetListeAppelParIdResponse")
    public List<Appel> getListeAppelParId(
        @WebParam(name = "arg0", targetNamespace = "")
        List<Long> arg0);

}
