
package mep.creation.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "TechniqueException", targetNamespace = "http://service.isiwebinterface.ass.inf.suo.fr/")
public class TechniqueException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private TechniqueException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public TechniqueException_Exception(String message, TechniqueException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public TechniqueException_Exception(String message, TechniqueException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: client.TechniqueException
     */
    public TechniqueException getFaultInfo() {
        return faultInfo;
    }

}
